### ISSUE TITLE
`pandas` ellipsis dots confuse the REPL

### ISSUE THREAD

**Issue by EpigeneMax** [sphinx-contrib/repl#1]
When displaying a large dataframe, `pandas` skips the middle part of the frame and figures the skip using ellipsis dots "...".
REPL can interpret them as an unfinished input prompt line, causing a shift in the output lines.

```rst
.. repl::
   import numpy as np
   import pandas as pd
   df = pd.DataFrame({"foo": np.arange(1000)})
   df.index = [f"longrowname{i}" for i in np.arange(1000)]
   df # the ellipsis dots occur here...
   print("Hello, world!") # ...and cause a shift from here on
   print("nothing")
```

results in
```
>>> import numpy as np
>>> import pandas as pd
>>> df = pd.DataFrame({'foo': np.arange(1000)})
>>> df.index = [f'longrowname{i}' for i in np.arange(1000)]
>>> df # the ellipsis dots occur here...
                foo
longrowname0      0
longrowname1      1
longrowname2      2
longrowname3      3
longrowname4      4
...
            ...
longrowname995  995
longrowname996  996
longrowname997  997
longrowname998  998
longrowname999  999

[1000 rows x 1 columns]
>>> print('Hello, world!') # ...and cause a shift from here on
>>> print('nothing')
Hello, world!
```

I don't know to fix this, but at least one can go around it by using `df.head()` when displaying large dataframes.

**Comment by tikuma-lsuhsc** [comment]
@EpigeneMax - I'm afraid that's a `pandas` feature and beyond the scope of `repl`. There seems to be a workaround though. Check out this link: https://dev.to/chanduthedev/how-to-display-all-rows-from-data-frame-using-pandas-dha

**Comment by EpigeneMax** [comment]
Totally agree, that's beyond the scope of `repl`.
I opened the issue to document the workaround, in case other people run into it.

Great tool, btw 👍

**Comment by tikuma-lsuhsc** [comment]
Thanks!

FYI, it would be better to post tips and techniques kind of stuff in Discussions instead of Issues as Issues becomes hard to find once closed.

**Comment by EpigeneMax** [comment]
My bad :/
Will do.
